### ISSUE TITLE
Peer to peer debugging

### ISSUE THREAD

**Issue by Yorsyboy** [HammadSiddique/My-Portfolio#15]
@HammadSiddique great job so fat 👍 but there are some bugs in the mobile menu and popup -windows, Kindly check the lines of code below in the Debugging branch.

- Line 19
- Line 123
- Between Line 122 and 123 there should be a reload method there 

Happy Coding 💯

**Comment by HammadSiddique** [comment]
Thank you for finding out my bugs, I'll solve them right away.
